management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

application-version: 1.0

server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin}@127.0.0.1:27017/produto
      auto-index-creation: true