server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/venda
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

services:
  produto:
    url: http://localhost:8082
  cliente:
    url: http://localhost:8081

application:
  produtoService:
    url: ${services.produto.url}
    endpointConsultarProduto: ${services.produto.url}/produto
  clienteService:
    url: ${services.cliente.url}
    endpointConsultarCliente: ${services.cliente.url}/cliente/isCadastrado/{id}
application-version: 2.0