server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:127.0.0.1}:27017/venda
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
