application-version=1.0.0
spring.application.name=ConfigServer
server.port=8888

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

spring.security.user.name=root
spring.security.user.password=${CONFIG_PASSWORD:root}

spring.devtools.livereload.enabled=false
